### ISSUE TITLE
Relisencing?

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#116]
I'm not sure the Parity experiment worked out that usefully for this project, or for its prospects for the future.

How do y'all members feel about changing the license such that _everything_ is under Apache-2.0 going forward?

@chrisdickinson @jlkiri @felipesere

**Comment by chrisdickinson** [comment]
Sounds good to me!

**Comment by felipesere** [comment]
Sounds good to me too.

**Comment by jlkiri** [comment]
I don't mind!

**Comment by zkat** [comment]
done. Thanks, all!
