### ISSUE TITLE
oro-client request retries

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#147]
oro-client should retry (some?) failed HTTP-requests. There's two nice crates that might do the trick here: backon or backoff. Either one will probably work, but backon looks nice?

**Comment by eryue0220** [comment]
Or can use the [reqwest-retry](https://crates.io/crates/reqwest-retry)? it has used the reqwest-middleware before

**Comment by zkat** [comment]
oh that might be good, yes!

**Comment by eryue0220** [comment]
Ok, I can solve this too

**Comment by zkat** [comment]
@eryue0220 just make sure it's controllable, and that it doesn't happen for "streamed" requests
