### ISSUE TITLE
write baseline tests for Nassun

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#155]
We don't have tests for any of Nassun's functionality! Fix this!

**Comment by DerNamenlose** [comment]
Hey. I'd be happy to lend a hand here, but I'd need a bit of guidance. What would you consider to be baseline tests here? Basically unit testing the `PackageResolver` or going full on integration with the NPM registry?

**Comment by zkat** [comment]
@DerNamenlose thanks for offering to help! I think the best place to start with this is to test an NPM resolution, then making sure you can get the packument/metadata, then making sure you can get the _tarball_ for those. Finally, you can test that tarball _extraction_ works, and you'll need to test both small tarballs (under 5mb), as well as larger tarballs (>5mb), since these are two different code paths.

There's an example of how to mock network requests and package metadata info over here: https://github.com/orogene/orogene/blob/main/crates/oro-client/src/api/packument.rs, and you can do something similar for tarball data--you'll want to either dynamically construct a tarball with tar-rs, or possibly easier, just have a pre-built fixture for it.

You don't need to do all of these right away, though. I would start by just scaffolding out the metadata tests and starting to put together PRs from there, unless you feel like doing everything in one fell swoop. Up to you :)

**Comment by DerNamenlose** [comment]
So, I've set up a draft PR (#196) to get a first feel whether this goes in the right direction. Please have a look and I'll continue working on the topic then.
