### ISSUE TITLE
Automatically write error log to a central location on error

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#179]
...also make it accessible in a clear way, somehow.

**Comment by kushalnl7** [comment]
Hi, I am interested in this. Can you please explain the issue and the required solution in a brief manner? Thanks!

**Comment by zkat** [comment]
Sure!

So, when NPM exits with an error, it actually writes an npm-debug.log file to the ~/.npm directory that you can check out for details, and that includes the results of logging at full log level ("silly" logging).

I'd like to have the same for orogene, so if there's a package manager error, there's an easy way to review what happened, without having to rerun the command on a higher log level by hand.

**Comment by zkat** [comment]
Update: I forgot you were thinking of doing it, and ended up doing it myself. Sorry!
