### ISSUE TITLE
figure out why reflinking fails on btrfs

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#193]
btrfs technically supports reflinking, and it's even documented over in ioctl: https://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html

Currently, we use the `reflink` crate to invoke this, and the call looks like this, which seems right to me: https://github.com/nicokoch/reflink/blob/master/src/sys/unix.rs#L21

Furthermore, this call *succeeds* on xfs on Linux, so it's not just that the Linux call itself is bad.

And so, this all fails on btrfs, with `EOPNOTSUPP`, which apparently means the file descriptor(s) don't support reflinking, which seems strange. Is this something that default btrfs installations don't support? Is the ioctl call wrong? We should investigate, because having reflinking in as many systems as possible is good for reliability _and_ perf.

The best way to test this is to run `cargo run -- restore --cache oro-cache --loglevel info` and looking at the log output from nassun. It should print out a message saying reflinks are going to be used. Instead, we get: `reflink support check failed. Files will be hard linked or copied. (Operation not supported (os error 95))`

**Comment by jokeyrhyme** [comment]
reflink only works in btrfs under specific conditions: https://btrfs.readthedocs.io/en/latest/Reflink.html

**Comment by jokeyrhyme** [comment]
I tried to reproduce, starting with `cargo new reflink-btrfs-test`

Cargo.toml:

```
[package]
name = "reflink-btrfs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflink = "0.1.3"
```

src/main.rs:

```
fn main() {
    match reflink::reflink("Cargo.toml", "Cargo.toml.reflink") {
        Ok(()) => println!("file has been reflinked"),
        Err(e) => println!("error while reflinking: {:?}", e),
    }
}
```

Then, running...

```
reflink-btrfs-test on  main [?] is 📦 v0.1.0 via 🦀 v1.67.1 took 55s
nu ❯ cargo run
   Compiling libc v0.2.139
   Compiling reflink v0.1.3
   Compiling reflink-btrfs-test v0.1.0 (/home/ron/reflink-btrfs-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `target/debug/reflink-btrfs-test`
file has been reflinked

reflink-btrfs-test on  main [?] is 📦 v0.1.0 via 🦀 v1.67.1
nu ❯ cat src/main.rs | wl-copy

reflink-btrfs-test on  main [?] is 📦 v0.1.0 via 🦀 v1.67.1
nu ❯ ls
╭───┬────────────────────┬──────┬─────────┬───────────────╮
│ # │        name        │ type │  size   │   modified    │
├───┼────────────────────┼──────┼─────────┼───────────────┤
│ 0 │ Cargo.lock         │ file │ 1.3 KiB │ 2 minutes ago │
│ 1 │ Cargo.toml         │ file │   205 B │ 2 minutes ago │
│ 2 │ Cargo.toml.reflink │ file │   205 B │ a minute ago  │
│ 3 │ src                │ dir  │    14 B │ 2 minutes ago │
│ 4 │ target             │ dir  │    66 B │ 2 minutes ago │
╰───┴────────────────────┴──────┴─────────┴───────────────╯
```

Some other information that may or may not be relevant:

```
nu ❯ mount | grep ' / '
/dev/mapper/root on / type btrfs (rw,relatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/@)

nu ❯ uname -a
Linux myhnegon 6.2.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 03 Mar 2023 15:58:31 +0000 x86_64 GNU/Linux
```

**Comment by zkat** [comment]
@jokeyrhyme just to make sure, do you get a successful reflink check if you run the orogene command above? I'm wondering if it's something about the way I'm doing it that's failing somehow...

**Comment by jokeyrhyme** [comment]
- okay, I've checked out https://github.com/orogene/orogene/commit/2bbd2616ed592486450d134dc4e8208b5de0a0a0
- and to test against, I checked out https://github.com/spacedriveapp/spacedrive/commit/23ad53867896b4f04ca2dc0aa603dad93df2ae69

1. in ~/GitHub/orogene/orogene: `cargo build`
2. in ~/GitHub/spacedriveapp/spacedrive: `~/GitHub/orogene/orogene/target/debug/oro restore --cache oro-cache --loglevel info`
3. ah, yes, I do see:

> 2023-03-08T19:07:52.347808Z  INFO nassun::tarball: reflink support check failed. Files will be hard linked or copied. (Operation not supported (os error 95))

intriguing...

**Comment by jokeyrhyme** [comment]
Okay, I'm new to thinking about reflinks this much, haha, but I think the issue is here: https://github.com/orogene/orogene/blob/main/crates/nassun/src/tarball.rs#L378

I suspect that the temporary directory/file created for this test is not on a btrfs volume?

For me:

```
nu ❯ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
```

Perhaps if the test used a file in the cache directory and a file in the node_modules directory instead? Or wherever the real reflinks will end up being?

It definitely feels a little inelegant to be creating temporary files outside of a temporary directory though

**Comment by jokeyrhyme** [comment]
If my theory is correct, you've now got me wondering why the test passes on XFS :shrug:

**Comment by zkat** [comment]
ooohhhhh I think you've got the right of it!! I feel really silly now, not realizing that tmpfile is probably creating files in a non-btrfs volume.

As far as why it passes on xfs, I have no idea either. Maybe the person who told me about xfs passing actually has /tmp in an xfs volume?

Either way, I guess the "clever" reflink check needs to be a little smarter. Hopefully while staying cheap to do.

**Comment by jokeyrhyme** [comment]
I think we need to adjust things a bit so that after we know the cache and node_modules paths, we use them for the reflink feature detection?

I think this is the trickiest part of the solution: right now, the code is nice and modular and isolated, and I haven't done enough high-performance Rust in production to really suggest how best to feed this information through without making it yucky, haha

**Comment by zkat** [comment]
I think the easiest way to do this is to move the reflink check one level up, into node-maintainer itself, which is the only place that's actually aware of node_modules as a _thing_ (nassun has no concept of it). Nassun can just accept a flag that's like "prefer copy", which is already there.

**Comment by zkat** [comment]
@jokeyrhyme I've landed a fix in main, and verified it myself on my Arch vm with btrfs. lmk if you're still not seeing things working!

**Comment by jokeyrhyme** [comment]
```
nu ❯ ~/GitHub/orogene/orogene/target/debug/oro restore --cache oro-cache --loglevel info
2023-03-09T08:35:22.460224Z  INFO orogene: Running command: /home/ron/GitHub/orogene/orogene/target/debug/oro restore --cache oro-cache --loglevel info
🔍 Resolved!
2023-03-09T08:35:22.711086Z  INFO node_maintainer::maintainer: Resolved graph of 306 nodes in 55ms
2023-03-09T08:35:22.722842Z  INFO node_maintainer::maintainer: Verified reflink support. Extracted data will use copy-on-write reflinks instead of hard links or full copies.
💾 ████████████████████████████████████████ [305/305] lodash@4.17.21 (https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz)                                                                                                                                                                                                                                                                                                               2023-03-09T08:35:22.895006Z  INFO node_maintainer::maintainer: Extracted 306 packages in 181ms.
💾 Linked!
2023-03-09T08:35:22.906723Z  INFO orogene: Ran in 0.459s
```

Wowzers, that is fast!

Thanks <3

**Comment by zkat** [comment]
@jokeyrhyme that's actually pretty slow. You're running in debug mode! :)
