### ISSUE TITLE
Benchmark setup

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#194]
We should have a general setup for benchmarking various package managers against each other (NPM, pnpm, Yarn, bun, orogene) in various scenarios, with the ability to generate graphs for results showing the difference.

The most important benchmarks to do are:

1. cold cache install with existing lockfile
2. warm cache install with existing lockfile
3. warm cache, existing lockfile, but for memory usage

I think those are the most important scenarios. There's a matrix of other situations, but they happen much more rarely than these two and I don't think they're worth analyzing or advertising.

I think these should be generated on Linux (xfs, btrfs or ext4) to begin with, but maybe we'll need to add Windows and macOS to that list later, because the performance profile is different (but orogene is still faster)

https://github.com/pnpm/benchmarks-of-javascript-package-managers might be a good starting point for all this.

**Comment by zkat** [comment]
Other thoughts: It might be nice to generate the benchmark data using [hyperfine](https://github.com/sharkdp/hyperfine). Here's a command line to test all of these scenarios and generate both a markdown table and a json data file to create graphs from:

```sh
hyperfine -p "rm -rf node_modules oro-cache ~/.bun/install/cache npm-cache pnpm-cache yarn-cache" \
    "oro restore --cache oro-cache" \
    "bun install" \
    "npm install --cache npm-cache --ignore-scripts" \
    "npx pnpm install --store-dir pnpm-cache --ignore-scripts" \
    "npx yarn --ignore-scripts --cache-folder yarn-cache"
```

(Yarn2/PnP tbd).

For the benchmark with cold caches, just remove the cache deletions in the first line.

**Comment by zkat** [comment]
This is done!

**Comment by cseas** [comment]
How did you benchmark memory usage? Were you able to find a CLI like hyperfine for it?

**Comment by zkat** [comment]
No, memory usage benchmarks were manual, using `/usr/bin/time -v`

**Comment by lukeed** [comment]
It would be nice if versions were included. Perhaps there are somewhere, but if so I'm unable to find them
