### ISSUE TITLE
[meta] make sure CI is caching cargo dependencies

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#228]
I'm not sure our CI is actually caching dependencies from crates.io, which means CI goes slower, and if crates.io is having issues, our CI has issues.

Would be nice to make sure things are getting cached and, if not, fix it.

**Comment by anurag-rajawat** [comment]
@zkat you're right our CI is not caching dependencies.
May I try this one?

**Comment by zkat** [comment]
@anurag-rajawat all yours!
