### ISSUE TITLE
Orogene logo/mascot

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#243]
Let's get a logo! This is a thread where folks can post their drafts/thoughts/ideas. Everyone else: go ahead and vote on what you think looks best! I'm not necessarily gonna pick the most popular, but it's something useful to take into account!

The theme of the logo should be "moving mountains".

**Comment by brandi-alexander** [comment]
Hey everyone I really loved Kat's idea and was really excited to give it a shot especially when she told me about the cute mascots she liked for reference, Ferris and the NPM wombat. 

I wanted to show some movement and was inspired by orogeny the creation of mountains. I wanted the main mountain to look like it was pulling in more mountains

Let me know what you think or anything you wanna see different 

![Asset 1@3x](https://user-images.githubusercontent.com/25859311/231894205-5ad34523-d1ff-4f1a-9cc0-6052bf6afdc9.png)

**Comment by chrisdickinson** [comment]
A couple of color variants:

![Orogene ](https://user-images.githubusercontent.com/37303/231894465-686befee-c6f8-4130-a496-c8f8a6ccdff9.png)
![Untitled_Artwork](https://user-images.githubusercontent.com/37303/231894468-b8d21203-c253-4a4b-a8cc-7dd5c2689f0e.png)

**Comment by danini-the-panini** [comment]
I'm not a graphic designer, but I like the idea of stylising the geological process of oregenesis itself into the logo:
![image](https://user-images.githubusercontent.com/1171825/237025358-88a84ee3-de6b-4a25-a58f-80a14970c0c8.png)

**Comment by zkat** [comment]
Thanks everyone for your submissions! These are all really great and I really truly appreciate everyone's time and creativity in submitting these!

Based on the votes, and tbh a bit of my own preference, I think we should go with @chrisdickinson's design! I particularly like the second color variant? It's definitely different from what I originally pictured but it looks really cool and I think fits the project really well.

So I guess next steps: @chrisdickinson, do you mind making a PR adding this logo to `./assets`? It would be nice to have both a png and an svg version of it (I'm assuming it's a vector image?).

**Comment by chrisdickinson** [comment]
> So I guess next steps: @chrisdickinson, do you mind making a PR adding this logo to `./assets`? It would be nice to have both a png and an svg version of it (I'm assuming it's a vector image?).

I wouldn't mind at all! I made this in ProCreate, so it's a layered raster image. I'll attach a large PNG and the original source file to the PR. It shouldn't be too hard to turn it into a vector image, but I might follow on with that in a subsequent PR (so if someone wants to, they can beat me to that!)
