### ISSUE TITLE
`node_modules/.bin` symlinks

### ISSUE THREAD

**Issue by silverwind** [orogene/orogene#269]
Would be nice to have these so tools like `npx` can use them. Or even better, provide a `npx`-like command to run these symlinks.

**Comment by zkat** [comment]
These should already be there. Can you confirm? Maybe this was posted before I added bin linking

**Comment by happysalada** [comment]
Just tried on orogene 0.3.27
and I can confirm there are no bin symlinks.
trying to run a script with npx returns
```
> npx vite dev

sh: line 1: vite: command not found
```
happy to provide a lockfile if you want to test, but any package.json with vite in it will work to reproduce the issue.

**Comment by zkat** [comment]
oh ahahha I see what's going on. Yes, I completely flubbed this. I'll fix it in a bit.
