### ISSUE TITLE
running cargo install orogene results in error

### ISSUE THREAD

**Issue by dvbnrg** [orogene/orogene#280]
Running cargo install orogene results in the following error:

   Compiling node-maintainer v0.3.27
error: invalid format string: field access isn't supported
   --> /home/justdave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/orogene-0.3.27/src/lib.rs:890:50
    |
890 |         Err(miette::miette!("Command not found: {self.command_name}"))
    |                                                  ^^^^^^^^^^^^^^^^^ not supported in format string
    |
help: consider using a positional formatting argument instead
    |
890 |         Err(miette::miette!("Command not found: {0}", self.command_name))
    |                                                  ~  +++++++++++++++++++

error: could not compile `orogene` (lib) due to previous error
error: failed to compile `orogene v0.3.27`, intermediate artifacts can be found at `/tmp/cargo-installmt5wfN`

**Comment by zkat** [comment]
This should all be fixed now.
