### ISSUE TITLE
Failed to extract tarball to cache on macOS

### ISSUE THREAD

**Issue by tido64** [orogene/orogene#295]
I tried to run `oro restore` in one of my repos and it failed to extract a package:

```
🔍 Resolved!
Error: nassun::cache::extract

  × Failed to extract tarball to cache. Failed to link cache contents from /~/Library/Caches/orogene/content-v2/sha256/b4/cd/12238114f78cbf58cd8cef3b25eee4cb40ff2d57fc3ebd5ff3a80c2eb131 to /~/Source/react-native-test-
  │ app/node_modules/http-proxy-agent/dist/index.js (file: /~/Source/react-native-test-app/node_modules/http-proxy-agent/dist/index.js)
  ├─▶ Failed to link cache contents from /~/Library/Caches/orogene/content-v2/sha256/b4/cd/12238114f78cbf58cd8cef3b25eee4cb40ff2d57fc3ebd5ff3a80c2eb131 to /~/Source/react-native-test-app/node_modules/http-proxy-agent/
  │   dist/index.js
  ╰─▶ File exists (os error 17)
```

It also looks like it stops at different files every time I retry `oro restore` without cleaning out first.

I have also occasionally seen this one (dunno if it's a different issue):

```
🔍 Resolved!
Error: nassun::io::extract

  × Failed to extract tarball while reading entry from tarball
  ╰─▶ failed to fill whole buffer
```

### Repro steps

```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
oro restore
```

This is a "hierarchical workspace" monorepo. I am aware that monorepos are currently not supported, but I was curious to see how far I can get.

### Version

```
% oro --version
orogene 0.3.4
```

### System info

```
System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Max
  Memory: 10.55 GB / 64.00 GB
  Shell:
    version: 3.6.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 18.18.0
    path: /private/var/folders/j0/5zfnwvyd4sb15smylklx03m00000gn/T/xfs-fff01f29/node
  Yarn:
    version: 3.6.1
    path: /private/var/folders/j0/5zfnwvyd4sb15smylklx03m00000gn/T/xfs-fff01f29/yarn
  npm:
    version: 9.8.1
    path: ~/.local/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
```

Let me know if you need any other info.

**Comment by zkat** [comment]
You're using a very old version of orogene. Do you mind updating to 0.3.31 and trying again? (restore is now called "apply" btw)

**Comment by tido64** [comment]
Doh! Apparently, I manually installed orogene under `~/.local/bin` a while back and forgot about it. I thought I upgraded it via `brew upgrade`, but now I also see that `brew install orogene` doesn't work:

```
Error: No available formula with the name "orogene".
```

Are the install instructions on the homepage still up to date?

**Comment by zkat** [comment]
Ah yeah I started generating brew stuff but I haven't published it to brew yet. That's `cargo-dist` stuff that I need to get around to. :)

**Comment by zkat** [comment]
Btw it’s available on brew now: brew install orogene/homebrew-tap/orogene

**Comment by tido64** [comment]
> Btw it’s available on brew now: brew install orogene/homebrew-tap/orogene

That's awesome! Thank you ❤️
