### ISSUE TITLE
Actually publish to brew

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#297]
we're generating brew-related artifacts now with the latest version of `cargo-dist`, but we're not actually uploading it to brew. Should probably figure out how to do that. If anyone wants to pick this up, I'd appreciate the help, especially if we can automate it :)

**Comment by jasikpark** [comment]
afaik, all you need is a git repo and a build command for homebrew, ex: https://github.com/Homebrew/homebrew-core/blob/master/Formula/n/nebula.rb

a formula is an instance of the Formulae class in ruby, which has a lot of default behavior, so it should be simple.

there's also automatic bots that will use https://docs.brew.sh/Brew-Livecheck to check for new versions, so it should be low-maintenance as long as the build api doesn't change

**Comment by jasikpark** [comment]
better rust example: https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/ripgrep.rb

**Comment by jasikpark** [comment]
the guide for what brew lints are wanted for a new formula: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up

**Comment by zkat** [comment]
fwiw, we already generate a formula: https://github.com/orogene/orogene/releases/tag/v0.3.31

so I guess this is just figuring out how to best create those PRs against brew and ideally automate the process.

**Comment by jasikpark** [comment]
hmm ig the advantage of automatically generating PRs from here is that they're closer to synchronous w/ release rather than relying on the homebrew git bot to generate a PR?

**Comment by mckern** [comment]
Following up on ^^: there's basically two options/paths: [you stick your homebrew formula that you're generating into a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) or you go through [their new formula process](https://docs.brew.sh/Adding-Software-to-Homebrew) and their bot will then monitor this repo and update their accepted formula (and all binary artifacts) automatically. But the formula you're generating will probably not be accepted by them as-is and you generally don't have to notify them that your repo has been updated unless you want ASAP updates on the formula they carry.

**Comment by jasikpark** [comment]
Put up https://github.com/Homebrew/homebrew-core/pull/147422 as a draft PR of option #2 - it definitely needs some work though :p

**Comment by zkat** [comment]
Linking cargo-dist's docs on doing this here: https://opensource.axo.dev/cargo-dist/book/installers/homebrew.html
