### ISSUE TITLE
Initial GUI designs

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#50]
We need some mockups/designs for what the GUI might look like, so we can get an idea of what we plan on actually implementing. My recommendation right now has been to base things somewhat on the VS NuGet UI, but I'll leave this at the discretion of whoever mocks this up.

Some example tasks that people need to do:

* Search for and install new packages
* Update/remove already-installed packages
* Preview package metadata

**Comment by superhawk610** [comment]
I've got some initial work for this going in Figma, if you'd like to contribute message me for an invite!

**Comment by taswyn** [comment]
Here to help! =)

**Comment by ZiQiLN** [comment]
I can perpare a clean design for package manager GUI, but I'm curious about technology on which GUI will be based, it will be os-native design or some modern-stack based UI?

**Comment by zkat** [comment]
@ZiQiLN you should link up with @taswyn and @superhawk610, since they're already working on a design. As far as what technology this is built on, we've settled on [Tauri](https://tauri.studio/en/), which is basically like Electron, but built on Rust and using native web views instead of shipping Chromium everywhere
