### ISSUE TITLE
API: Search

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#55]
Need a new crate that knows how to hit the NPM search endpoint. Basically need a clone of https://github.com/npm/libnpmsearch

A detailed description of the API endpoint and the data is returned is available here: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search

**Comment by mdarrik** [comment]
I would be interested in working on this, I think, if you're still looking for someone to take this.

**Comment by zkat** [comment]
@mdarrik all yours! Make sure to use `crates/oro-client` for it 👍🏻

**Comment by felipesere** [comment]
@mdarrik are you still working on this one? 😄

**Comment by mdarrik** [comment]
I've gotten a little side-tracked, but have been meaning to get back to it. I can probably dive back in this weekend. If it's blocking something you're working on, feel free to take over. I know you were working on some request stuff the other day.

**Comment by felipesere** [comment]
When #88 lands calling the search API should be easier. Let me know if you need any help!
