### ISSUE TITLE
Orogene missing logo

### ISSUE THREAD

**Issue by keinsell** [orogene/orogene#65]
Orogene missing logo, I've created issue to maybe find some potential ideas which can I use and create logo for this project.

**Comment by zkat** [comment]
cc @superhawk610

**Comment by superhawk610** [comment]
Hey @ZiQiLN, thanks for opening this issue! I've done some initial icon work you can view [at this link](https://www.figma.com/file/Jm6uWoGLIcPLEZheNiPXev/icons?node-id=0%3A1).

We're not 100% set on any particular theme yet, but I'll list some ideas here that you can work from:

- the project is named _orogene_ after the race from the [Broken Earth trilogy](https://broken-earth.fandom.com/wiki/Broken_Earth_Wiki) ([read more](https://broken-earth.fandom.com/wiki/Orogenes))
- the geological term [orogeny](https://en.wikipedia.org/wiki/Orogeny) refers to the formation of mountains by two or more continental plates push together and extend upwards
- first and foremost, orogene is a package manager, which often deals with _mountains of dependencies_ (*cue laughter*)
- if possible, we'd like an icon that's _cute_ (a cute volcano has been tossed around, for example)

Feel free to post your work in this issue thread, or if you're working in Figma let me know and I can add your work to our Figma project.

Looking forward to seeing what you come up with! :)

**Comment by ZiQiLN** [comment]
Sorry for the little lack of activity from my side, I just wanna say as a designer that I personally don't like an actual idea with Volcano since it's missing some aesthetics, what would you was about some cracked stone or maybe cracked package, that's also some kind of related to `orogene` name :)

**Comment by superhawk610** [comment]
Love it! Any ideas are OK at this point, we're still very early and have not decided anything for certain 🙂

**Comment by PressStart10** [comment]
how about this?
![Untitled](https://user-images.githubusercontent.com/73621363/99701274-3cca8900-2a62-11eb-8cb0-242e48556f30.jpg)

**Comment by zkat** [comment]
Hmm. What about something like a geode: 
![image](https://user-images.githubusercontent.com/17535/99888673-87373b80-2c03-11eb-9a76-f5493ae285cf.png)
