### ISSUE TITLE
Share your package.json!

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#98]
Hi all! I'm trying really hard as I write the resolver and all the various supporting libraries, to make sure that everything is compatible with the existing package ecosystem, and that the switch to Orogene ends up being as smooth as possible.

To that end, I'd love it if y'all shared some (anonymized as needed) example `package.json` files _from your applications_ (not libraries you maintain). The only bits I really need are the various dependency fields, so feel free to scrub everything else! I also obviously won't be able to access any private dependencies so those will need to go too.

tl;dr: ITT post some JSONs

**Comment by ianmcorvidae** [comment]
https://github.com/cyverse-de/sonora/blob/master/package.json is my contribution!

**Comment by EmmaRamirez** [comment]
Here's one from me, hope it helps
https://github.com/EmmaRamirez/nuzlocke-generator/blob/master/package.json

**Comment by stefee** [comment]
Here's a handful of edge cases:

- https://github.com/stefee/frogs/blob/17fd3fb230e2b284a348ccfe5966b2a445dc36f1/package.json
- https://github.com/stefee/stef-choo/blob/e7a9797073f89497263f9ec8d8fcd2fa565e5281/package.json
- https://github.com/CondeNast/hackathon2020-prominent-colors/blob/7ca6877a7fd5507b9a7677fc4ad44a0204bbf8de/package.json
- https://github.com/conde-nast-international/bundlesize/blob/36dcf48721c0cdfa7b4927d8d20c948a4afde8a4/package.json
- https://github.com/stefee/stef/blob/816634b930333795b460103b52ebad287a736065/package.json
- This one contains some private org packages so expect it to 403: https://github.com/CondeNast/gwa-atjson-playground/blob/1cfab029357e399378ef886e40d55f6c15d0a596/package.json

**Comment by copperwall** [comment]
Here's a few

https://github.com/iFixit/pulldasher/blob/master/package.json
https://github.com/iFixit/toolbox/blob/master/package.json
https://github.com/iFixit/prosemirror-wikitext/blob/master/package.json
